# Generated by Django 4.2 on 2023-05-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_eventcoordinator_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('approved', models.BooleanField(default=False)),
                ('block', models.BooleanField(default=False)),
                ('is_vender', models.BooleanField(default=True)),
                ('phone_number', models.CharField(max_length=255)),
                ('password', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
