# Generated by Django 4.2 on 2023-05-12 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_category_feature_venderitems_item_featurevalue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='featurevalue',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='featurevalue',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='CategoryFeature',
        ),
        migrations.DeleteModel(
            name='FeatureValue',
        ),
        migrations.AddField(
            model_name='itemfeature',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.feature'),
        ),
        migrations.AddField(
            model_name='itemfeature',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='features',
            field=models.ManyToManyField(through='app.ItemFeature', to='app.feature'),
        ),
    ]
