# Generated by Django 4.2 on 2023-05-16 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_item_category_alter_item_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='vender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.venders'),
        ),
        migrations.DeleteModel(
            name='VenderItems',
        ),
    ]
