# Generated by Django 4.2 on 2023-05-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_item_vender_delete_venderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcoordinator',
            name='location',
            field=models.CharField(default='calicut', max_length=200),
        ),
    ]
