# Generated by Django 4.2 on 2023-05-23 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_itemuserrend_event_alter_itemuserrend_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemuserrend',
            name='event',
        ),
        migrations.AlterField(
            model_name='itemuserrend',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.item'),
        ),
    ]
