# Generated by Django 4.2 on 2023-05-23 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_itemuserrend_event_alter_itemuserrend_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemuserrend',
            name='date_booked',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='EventUserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_booked', models.DateField(auto_now=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.eventcoordinator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
