# Generated by Django 4.2 on 2023-05-23 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_itemuserrend_date_booked_eventuserbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventuserbook',
            name='date_booked',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='itemuserrend',
            name='date_booked',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
