# Generated by Django 4.2 on 2023-05-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_eventuserbook_date_booked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
