# Generated by Django 4.2 on 2023-05-31 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_block_venders_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioEquipment',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.item')),
                ('equipment_type', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('power_rating', models.CharField(max_length=100)),
                ('additional_info', models.TextField()),
            ],
            bases=('app.item',),
        ),
        migrations.CreateModel(
            name='AudioVisualEquipment',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.item')),
                ('equipment_type', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('power_rating', models.CharField(max_length=100)),
                ('additional_info', models.TextField()),
            ],
            bases=('app.item',),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.item')),
                ('car_model', models.CharField(max_length=100)),
                ('car_type', models.CharField(max_length=100)),
                ('seating_capacity', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=100)),
                ('transmission_type', models.CharField(max_length=100)),
            ],
            bases=('app.item',),
        ),
        migrations.CreateModel(
            name='CateringEquipment',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.item')),
                ('equipment_type', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('power_rating', models.CharField(max_length=100)),
                ('additional_info', models.TextField()),
            ],
            bases=('app.item',),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FloorMat',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.item')),
                ('mat_material', models.CharField(max_length=100)),
                ('mat_type', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('pattern', models.CharField(max_length=100)),
            ],
            bases=('app.item',),
        ),
        migrations.CreateModel(
            name='FlowerDecoration',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.item')),
                ('flower_type', models.CharField(max_length=100)),
                ('color_scheme', models.CharField(max_length=100)),
                ('arrangement_style', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('additional_decor', models.TextField()),
            ],
            bases=('app.item',),
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.item')),
                ('furniture_type', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('additional_info', models.TextField()),
            ],
            bases=('app.item',),
        ),
        migrations.CreateModel(
            name='LightingEquipment',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.item')),
                ('equipment_type', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('power_rating', models.CharField(max_length=100)),
                ('additional_info', models.TextField()),
            ],
            bases=('app.item',),
        ),
        migrations.CreateModel(
            name='Platoon',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.item')),
                ('platoon_size', models.CharField(max_length=100)),
                ('platoon_type', models.CharField(max_length=100)),
                ('platoon_uniform', models.CharField(max_length=100)),
                ('performance_style', models.CharField(max_length=100)),
            ],
            bases=('app.item',),
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
            ],
        ),
        migrations.CreateModel(
            name='StageBackdrop',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.item')),
                ('backdrop_type', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('additional_info', models.TextField()),
            ],
            bases=('app.item',),
        ),
        migrations.RemoveField(
            model_name='itemfeature',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='itemfeature',
            name='item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='features',
        ),
        migrations.RemoveField(
            model_name='item',
            name='vender',
        ),
        migrations.RemoveField(
            model_name='itemuserrend',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.venders'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='ItemFeature',
        ),
        migrations.AddField(
            model_name='rental',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item'),
        ),
        migrations.AddField(
            model_name='itemuserrend',
            name='car_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.car'),
        ),
        migrations.AddField(
            model_name='itemuserrend',
            name='floor_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.floormat'),
        ),
        migrations.AddField(
            model_name='itemuserrend',
            name='flower_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.flowerdecoration'),
        ),
        migrations.AddField(
            model_name='itemuserrend',
            name='platoon_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.platoon'),
        ),
    ]
