# Generated by Django 4.2 on 2023-05-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_audioequipment_audiovisualequipment_car_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='client',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='item',
        ),
        migrations.AlterField(
            model_name='audioequipment',
            name='additional_info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='audioequipment',
            name='brand',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='audioequipment',
            name='equipment_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='audioequipment',
            name='power_rating',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='audiovisualequipment',
            name='additional_info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='audiovisualequipment',
            name='brand',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='audiovisualequipment',
            name='equipment_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='audiovisualequipment',
            name='power_rating',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='seating_capacity',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cateringequipment',
            name='additional_info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='cateringequipment',
            name='brand',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cateringequipment',
            name='equipment_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cateringequipment',
            name='power_rating',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='floormat',
            name='color',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='floormat',
            name='mat_material',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='floormat',
            name='mat_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='floormat',
            name='pattern',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='floormat',
            name='size',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='flowerdecoration',
            name='additional_decor',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='flowerdecoration',
            name='arrangement_style',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='flowerdecoration',
            name='color_scheme',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='flowerdecoration',
            name='flower_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='flowerdecoration',
            name='size',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='additional_info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='color',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='furniture_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='material',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lightingequipment',
            name='additional_info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='lightingequipment',
            name='brand',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lightingequipment',
            name='equipment_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lightingequipment',
            name='power_rating',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='platoon',
            name='performance_style',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='platoon',
            name='platoon_size',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='platoon',
            name='platoon_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='platoon',
            name='platoon_uniform',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='stagebackdrop',
            name='backdrop_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='stagebackdrop',
            name='color',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='stagebackdrop',
            name='size',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
