# Generated by Django 4.2 on 2023-05-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_rental_client_remove_rental_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imageUrl',
            field=models.CharField(default='', max_length=300),
        ),
    ]
