# Generated by Django 4.2 on 2023-06-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_item_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('Car', 'Car'), ('FlowerDecoration', 'Flower Decoration'), ('FloorMat', 'Floor Mat'), ('Platoon', 'Platoon'), ('AudioEquipment', 'AudioEquipment'), ('LightingEquipment', 'LightingEquipment'), ('StageBackdrop', 'StageBackdrop'), ('Furniture', 'Furniture'), ('AudioVisualEquipment', 'AudioVisualEquipment'), ('CateringEquipment', 'CateringEquipment')], default='', max_length=100),
        ),
    ]
