# Generated by Django 4.2 on 2023-06-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_itemuserrent_delete_itemuserrend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemuserrent',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
