# Generated by Django 4.2 on 2023-06-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemuserrent',
            name='payment_id',
            field=models.CharField(default='', max_length=300),
        ),
    ]
