# Generated by Django 4.2 on 2023-06-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_itemuserrent_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventuserbook',
            name='payment_id',
            field=models.CharField(default='', max_length=300),
        ),
    ]
