# Generated by Django 4.2 on 2023-06-09 06:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_eventuserbook_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventuserbook',
            name='date_bookedto',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
