# Generated by Django 4.2 on 2023-06-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_itemuserrent_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcoordinator',
            name='imageUrl',
            field=models.CharField(default='', max_length=300),
        ),
    ]
