# Generated by Django 4.2 on 2023-06-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_eventcoordinator_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcoordinator',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
