# Generated by Django 4.2 on 2023-06-11 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_eventcoordinator_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcoordinator',
            name='date_available',
        ),
    ]
