# Generated by Django 4.2 on 2023-06-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_venders_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='venders',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
