# Generated by Django 4.2 on 2023-06-13 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_venders_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinator',
            old_name='image',
            new_name='imageUrl',
        ),
    ]
