# Generated by Django 4.2 on 2023-06-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_rename_image_coordinator_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='imageUrl',
            field=models.CharField(default='', max_length=300),
        ),
    ]
