# Generated by Django 4.2 on 2023-06-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_coordinator_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='imageUrl',
            field=models.CharField(default='', max_length=300),
        ),
    ]
